format = """
[î‚¶](#FC5D7C)\
$username\
[î‚°](bg:#FC5D7C fg:#FC5D7C)\
$directory\
[î‚°](fg:#FC5D7C bg:#F39660)\
$git_branch\
$git_status\
[î‚°](fg:#F39660 bg:#8cb865)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[î‚°](fg:#8cb865 bg:#77bdd9)\
$time\
[î‚° ](fg:#77bdd9)\
"""


# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
# style_user = "bg:#9A348E"
# style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
# style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#FF6077"
format = "[ $path ]($style)"
truncation_length = 8
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜ "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#F39660"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#F39660"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[ocaml]
symbol = "ğŸ« "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#77bdd9"
format = '[ $time ]($style)'
